version: 2.1

description: Aura Testing Config for Circle CI
jobs:
  test:
    docker:
      - image: oven/bun:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - bun-modules-{{ checksum "bun.lockb" }}
      - run:
          name: Install dependencies
          command: bun install
      - save_cache:
          paths:
            - node_modules
          key: bun-modules-{{ checksum "bun.lockb" }}
      - run:
          name: Run Vitest Integration Tests
          command: bun run test-vite
      - store_test_results:
          path: ./test-results
      - store_artifacts:
          path: ./test-results

defaults:
  working_directory: ~/repo
