version: 2.1

description: Aura Testing Config for Circle CI

jobs:
  test:
    docker:
      - image: cimg/node:18.17
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "yarn.lock" }}
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_cache:
          paths:
            - node_modules
          key: node-modules-{{ checksum "yarn.lock" }}
      - run:
          name: Run Integration Tests
          command: yarn test:integration
      - store_test_results:
          path: ./test-results
      - store_artifacts:
          path: ./test-results

defaults:
  working_directory: ~/repo
